# Generated by Django 5.1.4 on 2024-12-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0002_blogarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
    ]
