# Generated by Django 5.1.4 on 2025-07-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0005_alter_course_content_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='registerblog',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
