# Generated by Django 5.1.4 on 2025-08-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reapp', '0006_blogarticle_slug_registerblog_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.ImageField(upload_to='voucher_images/')),
            ],
        ),
    ]
