[phases.setup]
cmds = [
  "apt-get update && apt-get install -y python3 python3-pip", # Install Python and pip
  "pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "python3 manage.py collectstatic --no-input"
]

[phases.start]
cmd = "python3 manage.py runserver 0.0.0.0:8000"

